name: 'Tests on PR'
on:
  pull_request:
    branches:
      - main
      - master

env:
  AWS_REGION: "ap-south-1"

permissions:
  id-token: write
  contents: read

jobs:
  lint-check:
    name: 'Lint check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v6
      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: 'Run lint checks'
        run: |
          npm ci --frozen-lockfile
          npm i -g turbo@^2
          turbo run lint

  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    needs: [lint-check]
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v6
      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: 'Run tests'
        run: |
          npm ci --frozen-lockfile
          npm i -g turbo@^2
          turbo run test
  
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: "arn:aws:iam::613419461354:role/GitHubAction-AssumeRoleWithAction"
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity