name: 'Lint check on PR'
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  lint-check:
    name: 'Lint check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v6
      - name: 'Setup node.js'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: 'Run lint checks'
        run: |
          npm ci --frozen-lockfile
          npm i -g turbo@^2
          turbo run lint