name: Post merge deploy to production
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: Terraform_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 --provenance=false -f ./apps/bablu/Dockerfile -t bablu:latest .
      - name: Tag Docker image
        run: docker tag bablu:latest ${{ secrets.ECR_URI }}:${{ github.sha }}
      - name: Push Docker image
        run: docker push ${{ secrets.ECR_URI }}:${{ github.sha }}
      - name: terraform apply
        id: apply
        uses: dflook/terraform-apply@v2.0.0
        with:
          path: './apps/bablu/terraform'
          variables: |
            image_tag=${{ github.sha }}
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}